name: Bug Report
description: File a bug report
title: "[ version of genshin ] [version of gimi] [version of raidenboss fix] error detail"
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ### DO NOT REMOVE OR SKIP THE ISSUE TEMPLATE
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I am using the latest version of the [Anime Game Remap](https://github.com/nhok0169/Anime-Game-Remap/releases/latest)
          required: true
        - label: I have searched [issues on Github](https://github.com/nhok0169/Anime-Game-Remap/issues) including closed ones and [issues on the mod site](https://gamebanana.com/tuts/15633) for similar issues. DO NOT post duplicates.
          required: true
        - label: I included a link to the mod that is producing the bug
          required: true
  - type: textarea
    id: description
    attributes:
      label: Provide a description that is worded well enough to be understood
      placeholder: Provide any additional information, any suggested solutions, and as much context and examples as possible
    validations:
      required: true
