name: Integration Tester

on: 
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  run-unit-tests:
    name: 'Integration Tests'
    uses: './.github/workflows/integration-test-workflow.yml'
