name: Code Change Checks

on: 
  [pull_request, push]

jobs:
  run-unit-tests:
    uses: './.github/workflows/unit-tests.yml'

  run-integration-tests:
    uses: './.github/workflows/integration-tests.yml'
