name: Upload FixRaidenBoss2 Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-unit-tests:
    uses: './.github/workflows/unit-test-workflow.yml'

  run-integration-tests:
    uses: './.github/workflows/integration-test-workflow.yml'

  publish-pypi:
    needs: [run-unit-tests, run-integration-tests]
    uses: './.github/workflows/publish-pypi-workflow.yml'
    permissions:
      id-token: write
    with:
      project_folder: './Anime Game Remap (for all users)/api'
      pypy_url: 'https://pypi.org/p/FixRaidenBoss2'
