on:
  workflow_call:

jobs:
  run-tests:
    name: Run Unit Tester
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Run Unit Tests
      run: python3 main.py
      working-directory: './Testing/Unit Tester'
    
